### ISSUE TITLE
Clean up error output

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022fa-420-LigmaPy#186]
I was getting some console messages while running the GUI, you should make sure this isn't happening with the final version. One I was seeing a lot was when I was trying to drag things:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/stephaniemschwartz/420-f22/2022fa-420-LigmaPy/view/View.py", line 1723, in dragMove
    x = widget.winfo_x() - widget.startX + event.x
AttributeError: 'Label' object has no attribute 'startX'

**Comment by aaheinba** [comment]
All of us tried to reproduce this error message, including professor Hobbs and were unable to.
